version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.16
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Run Tests
          command: npm test

      - persist_to_workspace:
          root: .
          paths:
            - .

  docker_build:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/repo

      - setup_remote_docker:
          version: 20.10.16

      - run:
          name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/node-js-sample:latest .

      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push your-dockerhub-username/node-js-sample:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
