version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.16
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Installer wait-on
          command: npm install -g wait-on

      - run:
          name: Start Application
          command: |
            npm run start &
      
      - run:
          name: Attendre que l'Application soit Disponible
          command: wait-on http://localhost:8080/

      - run:
          name: Test Application with curl
          command: |
            curl http://localhost:8080/ || { echo "L'application ne répond pas comme prévu."; exit 1; }

      - run:
          name: Tester l'Application avec curl
          command: |
            curl --fail http://localhost:8080/ || { echo "L'application ne répond pas comme prévu."; exit 1; }

      - persist_to_workspace:
          root: .
          paths:
            - .

  docker_build:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/repo

      - setup_remote_docker:
          version: 20.10.16

      - run:
          name: Build Docker Image
          command: |
            docker build -t mabule/node-js-sample:latest .

      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push mabule/node-js-sample:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
